
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Organic Ashwagandha',
    nameHindi: 'ऑर्गेनिक अश्वगंधा',
    description: 'Ancient medicinal herb known for reducing stress and anxiety. Sourced from the best farms in Madhya Pradesh.',
    price: 499,
    discountPrice: 399,
    offerPercentage: 20,
    category: 'supplements',
    image: 'https://picsum.photos/400/400?random=1',
    gallery: ['https://picsum.photos/400/400?random=1', 'https://picsum.photos/400/400?random=11'],
    rating: 4.8,
    benefits: ['Stress Relief', 'Improved Sleep', 'Energy Boost'],
    sku: 'ASH-001',
    stock: 50,
    inStock: true,
    isActive: true,
    tags: ['Stress', 'Herbal', 'Powder'],
    variants: [{ name: 'Size', options: ['100g', '250g'] }],
    createdAt: '2023-10-01T10:00:00Z',
    sales: 150
  },
  {
    id: '2',
    name: 'Pure Shilajit Resin',
    nameHindi: 'शुद्ध शिलाजीत',
    description: 'Natural substance found in the Himalayas, boosts energy and immunity. 100% Pure and Lab tested.',
    price: 999,
    category: 'supplements',
    image: 'https://picsum.photos/400/400?random=2',
    rating: 4.9,
    benefits: ['Stamina', 'Vitality', 'Immunity'],
    sku: 'SHI-002',
    stock: 20,
    inStock: true,
    isActive: true,
    tags: ['Energy', 'Resin', 'Men Health'],
    variants: [{ name: 'Weight', options: ['15g', '30g'] }],
    createdAt: '2023-11-15T10:00:00Z',
    sales: 85
  },
  {
    id: '3',
    name: 'Tulsi Ginger Tea',
    nameHindi: 'तुलसी अदरक चाय',
    description: 'A soothing blend of Holy Basil and Ginger for respiratory health. Perfect for immunity building.',
    price: 249,
    category: 'tea',
    image: 'https://picsum.photos/400/400?random=3',
    rating: 4.5,
    benefits: ['Digestion', 'Cold Relief', 'Antioxidant'],
    sku: 'TEA-003',
    stock: 100,
    inStock: true,
    isActive: true,
    tags: ['Tea', 'Immunity', 'Winter'],
    createdAt: '2023-09-01T10:00:00Z',
    sales: 320
  },
  {
    id: '4',
    name: 'Bhringraj Hair Oil',
    nameHindi: 'भृंगराज हेयर ऑयल',
    description: 'Traditional Ayurvedic oil for hair growth and scalp health. Infused with 12 herbs.',
    price: 399,
    discountPrice: 350,
    offerPercentage: 12,
    category: 'oils',
    image: 'https://picsum.photos/400/400?random=4',
    rating: 4.7,
    benefits: ['Hair Growth', 'Dandruff Control', 'Shine'],
    sku: 'OIL-004',
    stock: 45,
    inStock: true,
    isActive: true,
    tags: ['Hair Care', 'Oil', 'Growth'],
    createdAt: '2023-12-01T10:00:00Z',
    sales: 210
  },
  {
    id: '5',
    name: 'Triphala Powder',
    nameHindi: 'त्रिफला चूर्ण',
    description: 'A classic Ayurvedic herbal formulation for digestive health. Gentle and effective.',
    price: 199,
    category: 'supplements',
    image: 'https://picsum.photos/400/400?random=5',
    rating: 4.6,
    benefits: ['Digestion', 'Detox', 'Gut Health'],
    sku: 'TRI-005',
    stock: 0,
    inStock: false,
    isActive: true,
    tags: ['Digestion', 'Powder', 'Detox'],
    variants: [{ name: 'Pack', options: ['100g', '500g'] }],
    createdAt: '2024-01-05T10:00:00Z',
    sales: 95
  },
  {
    id: '6',
    name: 'Kumkumadi Tailam',
    nameHindi: 'कुंकुमादि तैलम',
    description: 'Miraculous beauty fluid for skin brightening and anti-aging. Saffron infused.',
    price: 1299,
    category: 'skincare',
    image: 'https://picsum.photos/400/400?random=6',
    rating: 4.9,
    benefits: ['Glowing Skin', 'Anti-Aging', 'Complexion'],
    sku: 'KUM-006',
    stock: 10,
    inStock: true,
    isActive: true,
    tags: ['Beauty', 'Face Oil', 'Glow'],
    createdAt: '2023-10-20T10:00:00Z',
    sales: 60
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'सभी (All)' },
  { id: 'supplements', label: 'सप्लीमेंट्स (Supplements)' },
  { id: 'tea', label: 'चाय (Tea)' },
  { id: 'oils', label: 'तेल (Oils)' },
  { id: 'skincare', label: 'त्वचा (Skincare)' },
];
